name: log_inspector
description: A comprehensive Flutter logging inspection package with cross-platform support, persistent storage, and customizable sharing options.
repository: https://github.com/thebedcoder/feature-manager/tree/master/packages/log_inspector
issue_tracker: https://github.com/thebedcoder/feature-manager/issues
homepage: https://github.com/thebedcoder/feature-manager

version: 1.0.3

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  file: ^7.0.1
  path_provider: ^2.1.5
  path: ^1.9.0
  share_plus: ^11.0.0
  idb_shim: ^2.6.1+7
  idb_sqflite: ^1.3.3+7
  sqflite: ^2.3.0
  web: ^1.1.1
  js_interop_utils: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
