name: fm_example
description: Example project for feature manager
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  feature_manager: ^4.0.0
  # feature_manager:
  #   path: ../../packages/feature_manager

  provider: ^6.1.2
  shared_preferences: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.15
  feature_manager_generator: ^4.0.0
  # feature_manager_generator:
  #   path: ../../packages/feature_manager_generator

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
