name: feature_manager_generator
description: Feature manager generator for developer preferences and experiments
repository: https://github.com/thebedcoder/feature-manager/tree/master/packages/feature_manager_generator
issue_tracker: https://github.com/thebedcoder/feature-manager/issues

version: 3.1.2

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:  
  analyzer: ^7.4.0
  build: ^3.0.0
  source_gen: ^3.0.0
  feature_manager: ^3.1.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
