name: feature_manager_generator
description: Feature manager generator for developer preferences and experiments
repository: https://github.com/thebedcoder/feature-manager/tree/master/packages/feature_manager_generator
issue_tracker: https://github.com/thebedcoder/feature-manager/issues

version: 4.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:  
  analyzer: ^9.0.0
  build: ^4.0.3
  source_gen: ^4.1.1
  feature_manager: ^4.0.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.14
