name: fmrc_example
description: Example project for remote_config_feature_manager
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  remote_config_feature_manager: ^4.0.0

  firebase_core: ^3.14.0
  firebase_remote_config: ^5.4.7
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  feature_manager_generator: ^4.0.0

dependency_overrides:
  win32: ^5.10.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
